name: Run DevOps Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run hello.sh script
      run: |
        chmod +x hello.sh
        ./hello.sh
